name: module_etamkawa
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  module_shared:
    path: ../Frontend.Mobile.Shared

  #  module_shared:
  #    git:
  #      url: https://buma.visualstudio.com/BUMA%20-%20BSpace%202.0/_git/Frontend.Mobile.Shared
  #      ref: v1.0.1-dev.21


  # module_shared:
  #   path: ../Frontend.Mobile.Shared
  #  module_lineup:
  #    path: ./Frontend.Mobile.Lineup

  flutter_riverpod: ^2.3.6
  riverpod_generator: ^2.3.5
  riverpod_annotation: ^2.1.1
  flutter_screenutil: 5.8.4
  percent_indicator: ^4.2.3
  syncfusion_flutter_charts: 23.2.4
  syncfusion_flutter_sliders: 23.2.4
  syncfusion_flutter_core: 23.2.4
  go_router: ^10.0.0
  internet_connection_checker: ^1.0.0+1
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0
  flutter_carousel_widget: ^2.1.0
  dio: ^5.3.2
  flutter_dotenv: ^5.1.0
  flutter_switch: ^0.3.2
  geocoding: ^2.1.0
  geolocator: ^10.0.1
  easy_tooltip: ^0.1.0
  dropdown_button2: ^2.3.9
  visibility_detector: ^0.4.0+2
  tutorial_coach_mark: ^1.2.9
  url_launcher: ^6.1.14
  easy_debounce: ^2.0.3
  scroll_date_picker: ^3.7.3
  flutter_background_service: ^5.0.2
  flutter_local_notifications: ^15.1.0+1
  ntp: ^2.0.0
  location: ^5.0.3
  flutter_inappwebview: ^6.0.0
  timeline_tile: ^2.0.0
  flutter_widget_from_html_core: ^0.14.7
  syncfusion_flutter_datagrid: 23.2.4
  lazy_load_indexed_stack: ^1.0.1
  icon_decoration: ^2.0.2
  workmanager: ^0.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.uat
    - .env
    - assets/images/
    - assets/images/general/



